# Funding options - uncomment and fill in your details
# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-open-collective
# ko_fi: your-ko-fi
# tidelift: npm/package-name
# custom: ["https://www.buymeacoffee.com/yourname"]